on: 
    push: 
        branches: ['main']

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            - name: Build Image And Push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/opal-web:latest
    
    deploy-api:
        runs-on: arisa-server
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Stop Opal API
              run: docker compose -f docker-compose.prod.yaml -p opal-api down opal-web --rmi all
              continue-on-error: true
          
            - name: Deploy API
              run: docker compose -f docker-compose.prod.yaml -p opal-api up -d opal-web